const projects = [
    {
        name: "Celesup",
        description:
            "A social media platform that simulates behavior of Facebook, Instagram and Twitter. With additional futures included",
        githubLink: "https://github.com/medmaha/celesup-c",
        downloadLink: "",
        liveDemoLink: "https://celesup.vercel.app",
        technologies: [""],
        thumbnail: "celesup.png",
    },
    {
        name: "REST Tester",
        description: "",
        githubLink: "https://github.com/medmaha/RestApiTester",
        downloadLink: "",
        liveDemoLink: "https://resttester.netlify.app",
        technologies: [""],
        thumbnail: "postman.png",
    },
    {
        name: "ChatVite",
        description: "",
        githubLink: "https://github.com/medmaha/chatvite.git",
        downloadLink: "",
        liveDemoLink: "https://chatvite.vercel.app",
        technologies: [""],
        thumbnail: "chatvite.png",
    },
    // {
    //     name: "Music App",
    //     description: "",
    //     githubLink: "",
    //     downloadLink: "",
    //     liveDemoLink: "",
    //     technologies: [""],
    // },
    // {
    //     name: "Spotify Clone",
    //     description: "",
    //     githubLink: "",
    //     downloadLink: "",
    //     liveDemoLink: "",
    //     technologies: [""],
    // },
    {
        name: "Path Finding Visualizer",
        description: "",
        githubLink: "",
        downloadLink: "",
        liveDemoLink: "https://pathfv.netlify.app/",
        technologies: [""],
        thumbnail: "path-visualizer.png",
    },
    // {
    //     name: "Fitness Master",
    //     description: "",
    //     githubLink: "",
    //     downloadLink: "",
    //     liveDemoLink: "",
    //     technologies: [""],
    // },
    // {
    //     name: "Sorting Algorithm Visualizer",
    //     description: "",
    //     githubLink: "",
    //     downloadLink: "",
    //     liveDemoLink: "",
    //     technologies: [""],
    // },
    {
        name: "MovieLand",
        description: "",
        githubLink: "https://github.com/medmaha/Movieland",
        downloadLink: "",
        liveDemoLink: "https://movieplant.netlify.app",
        technologies: [""],
        thumbnail: "movieland.png",
    },
    // {
    //     name: "E-commerce Site",
    //     description: "",
    //     githubLink: "",
    //     downloadLink: "",
    //     liveDemoLink: "",
    //     technologies: [""],
    //     thumbnail: "e-commerce.png",
    // },
    {
        name: "Tech Electrical",
        description: "",
        githubLink: "",
        downloadLink: "",
        liveDemoLink: "https://tec-electrical.netlify.app",
        technologies: [""],
        thumbnail: "tec-electrical.png",
    },
    // {
    //     name: "Google Clone",
    //     description: "",
    //     githubLink: "",
    //     downloadLink: "",
    //     liveDemoLink: "",
    //     technologies: [""],
    // },
    // {
    //     name: "Youtube Clone",
    //     description: "",
    //     githubLink: "",
    //     downloadLink: "",
    //     liveDemoLink: "",
    //     technologies: [""],
    // },
]

export default projects
