const projects = [
    {
        name: "Celehub",
        slug: "celehub",
        description: [
            "Celehub is a social media platform that allows supporters to connect with their favorite celebrities, while also providing a range of features that promote engagement and interactivity. The platform was designed to create a space where fans and celebrities can interact, share content, and engage in meaningful conversations.",
            "Built using the powerful combination of Django and NextJs, Celehub is a full-stack web application that offers robust functionality for both supporters and celebrities. Celehub is a scalable and performant application that prioritizes security and user experience.",
            "The platform employs a range of security measures, including secure authentication methods such as JWT tokens. Additionally, the platform uses a task queue like Celery to handle long-running or background tasks, such as sending emails or processing uploaded images, which helps improve the scalability and performance of the application.",
            "Another key feature of Celehub is its intuitive and engaging user interface styled with Tailwind Css. The platform is designed to be easy to use, with a clean and modern design that makes it simple for users to navigate and find the content they're looking for. App name changed from Celesup to Celehub",
        ],
        intro: "Celehub is a social media platform that allows supporters to connect with their favorite celebrities, while also providing a range of features that promote engagement and interactivity. The platform was designed to create a space where fans and celebrities can interact, share content, and engage in meaningful conversations.",
        githubLink: "https://github.com/medmaha/celesub",
        downloadLink: "",
        liveDemoLink: "https://celesub.vercel.app",
        technologies: [""],
        thumbnail: "celehub.png",
    },
    {
        name: "REST Tester",
        slug: "rest-tester",
        description: [
            "Rest Tester is an innovative web application that allows users to test RESTful APIs with ease and efficiency. The platform is designed to be intuitive and user-friendly, with a range of features that make it easy to test and modify API requests and responses.",
            "Built using Vanilla JavaScript and Axios, Rest Tester is a lightweight and powerful web application that provides a full-fledged custom code editor for JSON data. This makes it easy for users to create and modify JSON data, and to test their RESTful API requests with precision and accuracy.",
            " One of the key features of Rest Tester is its history record, which is stored in the user's browser storage for easy access and modification. This makes it easy for users to keep track of their API testing history and to make changes and adjustments as needed.",
            "To ensure maximum compatibility and efficiency, Rest Tester is compiled and bundled using Vite, a powerful build tool that provides fast and efficient compilation and bundling for web applications. This ensures that the application runs smoothly and efficiently on a range of different devices and platforms.",
            "Whether you're a developer looking to test your APIs or a user looking to interact with different RESTful services, Rest Tester provides a powerful and flexible platform for testing and debugging your API requests and responses.,",
        ],
        intro: "Rest Tester is an innovative web application that allows users to test RESTful APIs with ease and efficiency. The platform is designed to be intuitive and user-friendly, with a range of features that make it easy to test and modify API requests and responses.",
        githubLink: "https://github.com/medmaha/RestApiTester",
        downloadLink: "",
        liveDemoLink: "https://resttester.netlify.app",
        technologies: [""],
        thumbnail: "postman.png",
    },
    {
        name: "ChatVite",
        slug: "chatvite",
        description: [
            "ChatVite is a powerful web application that enables users to collaborate and chat together in an AI-powered chatroom. The platform is intuitive and engaging, with a range of features that promote interactivity and collaboration.",
            "Built using Next.js, MongoDb, SocketIo and other powerful technologies, ChatVite is a full-stack web application that provides a rich set of features for both public and private chatrooms. The platform includes features such as real-time chat, group and private chatroom creation, and AI-powered chatbots to keep conversations engaging and interactive.",
            "One of the primary goals of ChatVite is to provide a secure and private environment for users to collaborate and chat with one another. To that end, private chatrooms are only accessible to the host of the chatroom, ensuring that conversations are kept confidential and secure. Public chatrooms, on the other hand, are available to anyone who wishes to join and participate.",
            "To ensure the highest level of security and privacy for its users, ChatVite employs a range of security measures, including secure authentication methods such as JWT tokens and OAuth with the NextAuth library. Additionally, the platform uses Firebase Storage to securely store user media files, ensuring that user data is always safe and secure.",
        ],
        intro: "ChatVite is a powerful web application that enables users to collaborate and chat together in an AI-powered chatroom. The platform is intuitive and engaging, with a range of features that promote interactivity and collaboration.",
        githubLink: "https://github.com/medmaha/chatvite.git",
        downloadLink: "",
        liveDemoLink: "https://chatvite.vercel.app",
        technologies: [""],
        thumbnail: "chatvite.png",
    },
    {
        name: "Path Finder",
        slug: "path-finder",
        description: [
            "Pathfinding Visualizer is a web application that provides an intuitive interface for visualizing different search algorithms.",
            " One of the key features of Pathfinding Visualizer is its ability to visualize different search algorithms, including Dijkstra, A-star, breadth-first search, and depth-first search. This makes it easy for users to see how different search algorithms work and to compare their performance under different conditions.",
            " The user interface of Pathfinding Visualizer is designed to be clear and easy-to-understand visualizations that make it easy to see how the different search algorithms work.",
            "In terms of the tech stack, Pathfinding Visualizer is built using ReactJS, a powerful and flexible front-end framework that provides fast rendering and efficient updates. The app also uses Vanilla CSS, which allows for a high degree of customization and control over the visual appearance of the app.",
        ],
        intro: "Pathfinding Visualizer is a web application that provides an intuitive interface for visualizing different search algorithms. The user interface of Pathfinding Visualizer is designed to be clear and easy-to-understand visualizations that make it easy to see how the different search algorithms work. One of the key features of Pathfinding Visualizer is its ability to visualize different search algorithms",
        githubLink: "",
        downloadLink: "",
        liveDemoLink: "https://pathfv.netlify.app/",
        technologies: [""],
        thumbnail: "path-visualizer.png",
    },
    {
        name: "MovieLand",
        slug: "movie-land",
        description: [
            "MovieLand is a web application that allows users to search for and view information about movies. The app uses a third-party web API to retrieve a collection of movies based on the user's search query, and then displays this information in an intuitive and user-friendly interface.",
            "One of the key features of MovieLand is its ability to retrieve movie information asynchronously, providing a fast and responsive user experience. The app is built using ReactJS, a powerful and flexible front-end framework that provides fast rendering and efficient updates. It also uses Vanilla CSS to provide a high degree of customization and control over the visual appearance of the app.",
            "To use MovieLand, users simply type in the name of a movie they are interested in to the searchbar, and the app will search for and display information about that movie, including its title, release date, cast, and synopsis. Users can also browse through a collection of popular movies, and filter their search results based on various criteria, such as genre, rating, and release date.",
        ],
        intro: "MovieLand is a web application that allows users to search for and view information about movies. The app uses a third-party web API to retrieve a collection of movies based on the user's search query, and then displays this information in an intuitive and user-friendly interface.",
        githubLink: "https://github.com/medmaha/MovieLand",
        downloadLink: "",
        liveDemoLink: "https://movieplant.netlify.app",
        technologies: [""],
        thumbnail: "movieland.png",
    },
    {
        name: "Tech Electrical (TETI)",
        slug: "teti",
        description: [
            "TETI (Tech Electrical Training Institute) is a comprehensive website that provides technical training courses, sales of solar and electrical accessories, and services such as electrical and satellite installations. The website is built using SvelteKit, a powerful web framework that allows for seamless server-side rendering and efficient client-side updates.",
            "With SvelteKit, TETI's website is fast, responsive, and easy to use. Users can easily navigate the website to find information about TETI's various courses and services, including detailed descriptions, prices, and schedules. The website also provides users with the ability to register and enroll in courses, purchase products, and schedule service appointments.",
            "The website's integration with MongoDB allows for efficient data management, such as user account creation, course enrollment, and purchase history. The website also uses Tailwind CSS to create a modern and responsive design, allowing for seamless use on any device.",
            "TETI's website is designed with a modern, clean, and professional look, with intuitive navigation and user-friendly interfaces. It features a variety of interactive elements, such as forms, dropdown menus, and dynamic content, to enhance the user experience.",
            "Overall, TETI's website is a powerful tool for both TETI and its customers, providing a seamless and efficient online experience for technical training, product purchases, and services",
        ],
        intro: "TETI (Tech Electrical Training Institute) is a comprehensive website that provides technical training courses, sales of solar and electrical accessories, and services such as electrical and satellite installations. The website is built using SvelteKit, a powerful web framework that allows for seamless server-side rendering and efficient client-side updates. MongoDB is used as the database to store and manage data. Tailwind CSS is used to style the website and create a responsive and modern design.",
        githubLink: "https://github.com/medmaha/tech-electric",
        downloadLink: "",
        liveDemoLink: "https://tech-electric.vercel.app",
        technologies: [""],
        thumbnail: "tec-electrical.png",
    },
]
export { projects }
